spring:
  datasource:
    url: jdbc:mysql://localhost:3306/readme_store?createDatabaseIfNotExist=true
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: set_username
    password: set_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true